"""Fix tipos de claves

Revision ID: 1532ba96264a
Revises: 
Create Date: 2025-06-06 21:56:47.587840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1532ba96264a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relacion_tablas', schema=None) as batch_op:
        batch_op.alter_column('sintoma_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('enfermedad_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('recomendacion_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'sintomas', ['sintoma_id'], ['id_sintomas'])
        batch_op.create_foreign_key(None, 'enfermedades', ['enfermedad_id'], ['id_enfermedad'])
        batch_op.create_foreign_key(None, 'recomendaciones', ['recomendacion_id'], ['id_recomendacion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relacion_tablas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('recomendacion_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('enfermedad_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('sintoma_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
