"""Migracion inicial limpia

Revision ID: 247baf76c7b5
Revises: 
Create Date: 2026-01-25 11:03:32.445305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247baf76c7b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfermedades',
    sa.Column('id_enfermedad', sa.Integer(), nullable=False),
    sa.Column('enfermedad', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_enfermedad')
    )
    op.create_table('recomendaciones',
    sa.Column('id_recomendacion', sa.Integer(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_recomendacion')
    )
    op.create_table('sintomas',
    sa.Column('id_sintomas', sa.Integer(), nullable=False),
    sa.Column('sintomas', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_sintomas')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('tamano', sa.String(length=50), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relacion_tablas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sintoma_id', sa.Integer(), nullable=False),
    sa.Column('enfermedad_id', sa.Integer(), nullable=False),
    sa.Column('recomendacion_id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['enfermedad_id'], ['enfermedades.id_enfermedad'], ),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones.id_recomendacion'], ),
    sa.ForeignKeyConstraint(['sintoma_id'], ['sintomas.id_sintomas'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('sintomas', sa.Text(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=False),
    sa.Column('contexto_anterior', sa.Text(), nullable=False),
    sa.Column('enfermedad', sa.Text(), nullable=False),
    sa.Column('alerta', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_diagnostico_id'), 'historial_diagnostico', ['id'], unique=False)
    op.create_table('seguimiento_mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mascota_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('raza', sa.String(length=120), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento_mascota')
    op.drop_index(op.f('ix_historial_diagnostico_id'), table_name='historial_diagnostico')
    op.drop_table('historial_diagnostico')
    op.drop_table('relacion_tablas')
    op.drop_table('mascotas')
    op.drop_table('usuarios')
    op.drop_table('sintomas')
    op.drop_table('recomendaciones')
    op.drop_table('enfermedades')
    # ### end Alembic commands ###
