"""Cambios en tabla recomendacion

Revision ID: 2d0118e8d649
Revises: 1532ba96264a
Create Date: 2025-06-07 16:00:22.577474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0118e8d649'
down_revision = '1532ba96264a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomendaciones', schema=None) as batch_op:
        batch_op.alter_column('recomendacion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomendaciones', schema=None) as batch_op:
        batch_op.alter_column('recomendacion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
