"""Cambio en modelo mascotas

Revision ID: aaf7524e79e5
Revises: c4706ae5913c
Create Date: 2025-06-12 10:29:33.870041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf7524e79e5'
down_revision = 'c4706ae5913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.drop_column('especie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especie', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=False))

    # ### end Alembic commands ###
