"""Añadir alerta y enfermedad en tabla historial

Revision ID: c07c50ed702c
Revises: edb16be74bf3
Create Date: 2025-07-29 11:03:32.346737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07c50ed702c'
down_revision = 'edb16be74bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_diagnostico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enfermedad', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('alerta', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_diagnostico', schema=None) as batch_op:
        batch_op.drop_column('alerta')
        batch_op.drop_column('enfermedad')

    # ### end Alembic commands ###
