"""Implementaciones

Revision ID: c4706ae5913c
Revises: 87efd5a99d4e
Create Date: 2025-06-11 13:49:34.227250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4706ae5913c'
down_revision = '87efd5a99d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_diagnostico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contexto_anterior', sa.Text(), nullable=False))

    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamano', sa.String(length=50), nullable=True))
        batch_op.drop_column('tamaño')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamaño', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=50), nullable=True))
        batch_op.drop_column('tamano')

    with op.batch_alter_table('historial_diagnostico', schema=None) as batch_op:
        batch_op.drop_column('contexto_anterior')

    # ### end Alembic commands ###
