"""Remove Recomendaciones de Relcion tablas

Revision ID: ea67252311d3
Revises: 247baf76c7b5
Create Date: 2026-01-30 21:09:15.355632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea67252311d3'
down_revision = '247baf76c7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacion_tablas', sa.Column('recomendacion', sa.Text(), nullable=False))
    op.drop_constraint(None, 'relacion_tablas', type_='foreignkey')
    op.drop_column('relacion_tablas', 'recomendacion_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relacion_tablas', sa.Column('recomendacion_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'relacion_tablas', 'recomendaciones', ['recomendacion_id'], ['id_recomendacion'])
    op.drop_column('relacion_tablas', 'recomendacion')
    # ### end Alembic commands ###
